-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."EmailVerification"
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    verification boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Employees"
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Employers"
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_site character varying(50) NOT NULL,
    phone_number character(12) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."JobSeekers"
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id character(11) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."MernisVerification"
(
    id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    verfication boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Title"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Users"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

ALTER TABLE public."Employees"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."MernisVerification"
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public."JobSeekers" (user_id)
    NOT VALID;

END;