name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Setup PostgreSQL
       - uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 14

          postgresql db: hrms

          postgresql user: postgres

          postgresql password: password

      - name: Build with Maven
        run: mvn -B package --file pom.xml
